### ISSUE TITLE
unexpected behavior of FlattenRegisters on classicalexpbox

### ISSUE THREAD

**Issue by cqc-melf** [CQCL/tket#850] opened 2023-05-02 14:18 UTC
```
circ = Circuit(3)
a = circ.add_c_register("a", 5)
b = circ.add_c_register("b", 5)
c = circ.add_c_register("c", 5)
circ.add_classicalexpbox_register(a | b, c)

print(circ.to_dict())
FlattenRegisters().apply(circ)
print(circ.to_dict())
```

returns 

{'bits': [['a', [0]], ['a', [1]], ['a', [2]], ['a', [3]], ['a', [4]], ['b', [0]], ['b', [1]], ['b', [2]], ['b', [3]], ['b', [4]], ['c', [0]], ['c', [1]], ['c', [2]], ['c', [3]], ['c', [4]]], 'commands': [{'args': [['a', [0]], ['a', [1]], ['a', [2]], ['a', [3]], ['a', [4]], ['b', [0]], ['b', [1]], ['b', [2]], ['b', [3]], ['b', [4]], ['c', [0]], ['c', [1]], ['c', [2]], ['c', [3]], ['c', [4]]], 'op': {'box': {'exp': {'args': [{'name': 'a', 'size': 5}, {'name': 'b', 'size': 5}], 'op': 'RegWiseOp.OR'}, 'id': '2d953900-13a7-4512-b28f-f187085eb961', 'n_i': 10, 'n_io': 0, 'n_o': 5, 'type': 'ClassicalExpBox'}, 'type': 'ClassicalExpBox'}}], 'created_qubits': [], 'discarded_qubits': [], 'implicit_permutation': [[['q', [0]], ['q', [0]]], [['q', [1]], ['q', [1]]], [['q', [2]], ['q', [2]]]], 'phase': '0.0', 'qubits': [['q', [0]], ['q', [1]], ['q', [2]]]}

{'bits': [['c', [0]], ['c', [1]], ['c', [2]], ['c', [3]], ['c', [4]], ['c', [5]], ['c', [6]], ['c', [7]], ['c', [8]], ['c', [9]], ['c', [10]], ['c', [11]], ['c', [12]], ['c', [13]], ['c', [14]]], 'commands': [{'args': [['c', [0]], ['c', [1]], ['c', [2]], ['c', [3]], ['c', [4]], ['c', [5]], ['c', [6]], ['c', [7]], ['c', [8]], ['c', [9]], ['c', [10]], ['c', [11]], ['c', [12]], ['c', [13]], ['c', [14]]], 'op': {'box': {'exp': {'args': [**{'name': 'a', 'size': 5}, {'name': 'b', 'size': 5}**], 'op': 'RegWiseOp.OR'}, 'id': '2d953900-13a7-4512-b28f-f187085eb961', 'n_i': 10, 'n_io': 0, 'n_o': 5, 'type': 'ClassicalExpBox'}, 'type': 'ClassicalExpBox'}}], 'created_qubits': [], 'discarded_qubits': [], 'implicit_permutation': [[['q', [0]], ['q', [0]]], [['q', [1]], ['q', [1]]], [['q', [2]], ['q', [2]]]], 'phase': '0.0', 'qubits': [['q', [0]], ['q', [1]], ['q', [2]]]}

this shows that the classicalexpbox still wants to be used on the registers a and b which are not existing any more?

**Comment by yao-cqc** [comment] 2023-05-05 10:30
This is due to `FlattenRegisters` not modifying the python object within `ClassicalExpBox`. This can be fixed by reimplement `flatten_registers` to use `rename_units` since `rename_units` does modifies the python objects. However I'm not sure what is the expected behaviour for the example shown here. Since registers a, b, c are involved in a register-wise expression and you can't really merge these into one register, `rename_units` will raise an exception. Should `flatten_registers` raise an exception as well? Or should it leave these classical registers untouched but flatten all other registers? @cqc-alec

**Comment by cqc-alec** [comment] 2023-05-05 11:41
I think that as the underlying operation is a `RegWiseOp` it _should_ probably be an error to call `FlattenRegisters()` on this circuit. So maybe making `flatten_registers` call `rename_units` is the right thing to do -- in this case it would be an error but in other cases it wouldn't be (if the operation were acting on bits rather than registers). (So we should add two test cases -- one as above which is expected to raise and exception, and one (using a `BitLogicExp`) that is expected to succeed?)

**Comment by yao-cqc** [comment] 2023-05-05 13:20
Is it OK to throw an error? Do we have any pass that can throw an error during execution? I know pass can throw if there are unsatisfied predicates.

**Comment by yao-cqc** [comment] 2023-05-05 13:20
ah, looks like `DelayMeasures` can throw errors.

**Comment by cqc-alec** [comment] 2023-05-05 13:30
Yes I think there are some cases, as predicates can't capture all failure modes.

**Closed** 2023-05-12 16:15 UTC
Labels: bug
